apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet

      nodeSelector:
        node-role.kubernetes.io/master: "true"

      tolerations:
        - effect: NoExecute
          key: CriticalAddonsOnly
          operator: "Exists"

      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1

      resources:
        requests:
          cpu: 75m
          memory: 128M
        limits: {}
