# https://docs.rke2.io/install/install_options/install_options/#configuration-file
# https://docs.rke2.io/install/install_options/server_config/

node-taint:
  - "CriticalAddonsOnly=true:NoExecute"

etcd-snapshot-schedule-cron: "* */6 * * *"
etcd-snapshot-retention: 20

control-plane-resource-requests: kube-apiserver-cpu=75m,kube-apiserver-memory=128M,kube-scheduler-cpu=75m,kube-scheduler-memory=128M,kube-controller-manager-cpu=75m,kube-controller-manager-memory=128M,kube-proxy-cpu=75m,kube-proxy-memory=128M,etcd-cpu=75m,etcd-memory=128M,cloud-controller-manager-cpu=75m,cloud-controller-manager-memory=128M
#control-plane-resource-limits
